### ISSUE TITLE
Population-density: Unable to download

### ISSUE THREAD

**Issue by Rikuoja** [kuwala-io/kuwala#32]
Hello everybody, and thanks for creating a promising new tool! In the process of benchmarking such tools right now, just a quick tryout out of the box resulted in this issue
```
[z] IT - Italy
[0] Next page

Please select a country! [1...9, a...z, 0]: 2
Downloading data for Finland
Error: No data available for FIN
    at /opt/app/src/utils/countryPicker/index.js:19:17
    at new Promise (<anonymous>)
    at downloadFiles (/opt/app/src/utils/countryPicker/index.js:7:12)
    at /opt/app/src/utils/countryPicker/index.js:86:23
    at new Promise (<anonymous>)
    at Object.pick (/opt/app/src/utils/countryPicker/index.js:41:12)
    at /opt/app/src/data/processor/index.js:101:49
    at new Promise (<anonymous>)
    at Object.start (/opt/app/src/data/processor/index.js:99:12)
    at /opt/app/src/data/main.js:43:41
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
 ```
    
The problem was mentioned in https://github.com/kuwala-io/kuwala/pull/23#issuecomment-852154286 , but that PR is already merged, so apparently it didn't resolve the issue for all users.

**Comment by mattigrthr** [comment]
Hi @Rikuoja, thanks for posting this issue. I see that you tried to download the data for Finland. Unfortunately, there are still some countries that Facebook doesn't cover yet with their project. For Sweden, we know, for example, that due to the high latitude, the satellite image distortion posed a challenge in the beginning. Also, too cloudy satellite images have an impact. I guess it's a similar case with Finland. However, Facebook actively improves its coverage. They told us that they are about to release data for Sweden (and hopefully also Finland). They have an [RSS feed](https://dataforgood-fb-data.s3.amazonaws.com/hrsl-cogs/rss_feed.xml) you can follow to get the updates.

Nevertheless, I do get that it's a bad user experience to receive this error. We listed all countries using the `i18n-iso-countries` npm package. But we could use the AWS CLI to only list countries where data is available. I will create a separate issue for that. In the meantime, you can list the available countries in your terminal if you have the AWS CLI installed, running the following command:

```
aws s3 ls --no-sign-request s3://dataforgood-fb-data/csv/month=2019-06/
```

To test it out quickly, you can pick a small country like Malta.

**Comment by Rikuoja** [comment]
@mattigrthr Thanks for the quick answer! Good to know that this is actually a real error, i.e. the reason I am not getting data from Finland is only that the data is not available yet :D I was afraid there was something else wrong.

**Comment by mattigrthr** [comment]
The issue regarding the UX is #34
