### ISSUE TITLE
Running demo on Windows

### ISSUE THREAD

**Issue by IritaSee** [kuwala-io/kuwala#62]
Hello! 
I found that if you run the demo using this line 
```bash
cd kuwala/scripts && sh initialize_core_components.sh && sh run_cli.sh
```
On docker desktop for Windows, it founds an error:
```
sh: 0: Can't open build_neo4j.sh
sh: 0: Can't open build_cli.sh
build_jupyter_notebook.sh: 1: cd: can't cd to ..
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 153, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 222, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
[7178] Failed to execute script docker-compose
```

I assume that the bash script is not fully compatible with Windows filesystem... Any idea for this? 

Thank you ^^

**Comment by mattigrthr** [comment]
The demo is not running on Windows out of the box. The existing command `cd kuwala/scripts && sh initialize_core_components.sh && sh run_cli.sh
` was designed for Mac/Linux.

The prerequisites stay the same. People have to have Python3 (along with pip) installed, have downloaded Docker Desktop and launched it in the background.

The necessary adjustments to get it running on Windows are:

1. Create a new script for windows in the manner of the one above that doesn't use `sh` since that is not supported on Windows.
2. Activating the virtual environment likely uses a different command on Windows.
3. Some pip packages from the `requirements.txt` of the CLI might have Windows-specific issues.

**Comment by IritaSee** [comment]
To make life easier, I am going to "translate" all of the scripts so it is readable by windows system. The main problem came from `cd` command, got this idea when looking at the error:
``` build_neo4j.sh: line 1: cd: $'..\r': No such file or directory ```

windows used `\r\n` as the line ending in their filesystem, so whenever we modify things in windows (without customizing the line ending in our editor), it will (by default) saved the file using `\r\n` line ending. In order for us to run the `bash` script **inside windows,** we need to change the `\r\n` ending format to simply just `\n` just like in unix filesystem.

Currently I am working on a branch for this ^^

**Comment by IritaSee** [comment]
It seems like we need extra `cd .. ` in every converted code, since all of the converted code is in `/windows`

**Comment by Lance0404** [comment]
Hi all, I have encountered a different issue. 

I'm merely touching the surface of this great project. Here is some issues I ran into while installing with this command:
`cd kuwala/scripts && sh initialize_core_components.sh && sh run_cli.sh`
And it turns out the error roots from `sh build_cli.sh`.
For the past 2 years, I mostly expect WSL2 ubuntu working as normal ubuntu.
I suppose this shouldn't have relation with docker, so I didn't paste infomation related to docker.

My spec:
OS: win10 WSL2 Ubuntu-20.04
Python version: 3.10.2
Pip version: pip 22.0.3 from /home/lance/.local/lib/python3.10/site-packages/pip (python 3.10)
I am currently no expert with `setup.py`.

I will have the whole stderr pasted here.

```
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: virtualenv in /home/lance/.local/lib/python3.10/site-packages (20.13.1)
Requirement already satisfied: distlib<1,>=0.3.1 in /home/lance/.local/lib/python3.10/site-packages (from virtualenv) (0.3.4)
Requirement already satisfied: platformdirs<3,>=2 in /home/lance/.local/lib/python3.10/site-packages (from virtualenv) (2.5.0)
Requirement already satisfied: filelock<4,>=3.2 in /home/lance/.local/lib/python3.10/site-packages (from virtualenv) (3.4.2)
Requirement already satisfied: six<2,>=1.9.0 in /home/lance/.local/lib/python3.10/site-packages (from virtualenv) (1.16.0)
created virtual environment CPython3.10.2.final.0-64 in 230ms
  creator CPython3Posix(dest=/home/lance/opensource/kuwala/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/lance/.local/share/virtualenv)
    added seed packages: PyYAML==5.4.1, SQLAlchemy==1.4.22, Unidecode==1.2.0, altgraph==0.17, attrs==21.2.0, basicauth==0.4.1, beautifulsoup4==4.9.3, boto3==1.18.19, botocore==1.21.19, cchardet==2.1.7, certifi==2021.5.30, cffi==1.14.6, chardet==4.0.0, charset_normalizer==2.0.4, ckanapi==4.6, click==8.0.1, colorlog==5.0.1, coverage==5.5, cryptography==3.4.7, cssselect==1.1.0, decorator==5.0.9, dnspython==2.1.0, docopt==0.6.2, email_validator==1.1.3, et_xmlfile==1.1.0, exchangerates==0.3.4, fuzzywuzzy==0.18.0, greenlet==1.1.1, hdx_python_api==5.2.4, hdx_python_country==2.9.5, hdx_python_utilities==2.6.9, html5lib==1.1, idna==3.2, ijson==3.1.4, inflect==5.3.0, iniconfig==1.1.1, itsdangerous==2.0.1, jmespath==0.10.0, jsonlines==2.0.0, jsonpath_ng==1.5.3, libhxl==4.24.1, linear_tsv==1.1.0, lxml==4.6.3, macholib==1.15.1, ndg_httpsclient==0.5.1, num2words==0.5.10, openpyxl==3.0.7, packaging==21.0, pip==22.0.3, pluggy==0.13.1, ply==3.11, pprintpp==0.4.0, prompt_toolkit==3.0.19, py==1.10.0, pyOpenSSL==20.0.1, pyasn1==0.4.8, pycountry==20.7.3, pycountry_convert==0.7.2, pycparser==2.20, pyinstaller==4.5.1, pyinstaller_hooks_contrib==2021.3, pyparsing==2.4.7, pyphonetics==0.5.3, pyquery==1.4.3, pytest==6.2.4, pytest_cov==2.12.1, pytest_mock==3.6.1, python_Levenshtein_wheels==0.13.2, python_dateutil==2.8.2, python_io_wrapper==0.2, python_slugify==5.0.2, quantulum3==0.7.7, questionary==1.10.0, ratelimit==2.2.1, repoze.lru==0.7, requests==2.26.0, requests_cache==0.7.3, requests_file==1.5.1, ruamel.yaml.clib==0.2.6, ruamel.yaml==0.17.10, s3transfer==0.5.0, setuptools==60.6.0, six==1.16.0, soupsieve==2.2.1, tabulator==1.53.5, text_unidecode==1.3, toml==0.10.2, tqdm==4.62.0, unicodecsv==0.14.1, url_normalize==1.4.3, urllib3==1.26.6, wcwidth==0.2.5, webencodings==0.5.1, websocket_client==1.2.1, wheel==0.37.1, xlrd3==1.1.0, xlrd==2.0.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
build_cli.sh: 4: source: not found
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: altgraph==0.17 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 1)) (0.17)
Requirement already satisfied: attrs==21.2.0 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 2)) (21.2.0)
Requirement already satisfied: basicauth==0.4.1 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 3)) (0.4.1)
Requirement already satisfied: beautifulsoup4==4.9.3 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 4)) (4.9.3)
Requirement already satisfied: boto3==1.18.19 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 5)) (1.18.19)
Requirement already satisfied: botocore==1.21.19 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 6)) (1.21.19)
Requirement already satisfied: cchardet==2.1.7 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 7)) (2.1.7)
Requirement already satisfied: certifi==2021.5.30 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 8)) (2021.5.30)
Requirement already satisfied: cffi==1.14.6 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 9)) (1.14.6)
Requirement already satisfied: chardet==4.0.0 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 10)) (4.0.0)
Requirement already satisfied: charset-normalizer==2.0.4 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 11)) (2.0.4)
Requirement already satisfied: ckanapi==4.6 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 12)) (4.6)
Requirement already satisfied: click==8.0.1 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 13)) (8.0.1)
Requirement already satisfied: colorlog==5.0.1 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 14)) (5.0.1)
Requirement already satisfied: coverage==5.5 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 15)) (5.5)
Requirement already satisfied: cryptography==3.4.7 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 16)) (3.4.7)
Requirement already satisfied: cssselect==1.1.0 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 17)) (1.1.0)
Requirement already satisfied: decorator==5.0.9 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 18)) (5.0.9)
Requirement already satisfied: dnspython==2.1.0 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 19)) (2.1.0)
Requirement already satisfied: docopt==0.6.2 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 20)) (0.6.2)
Requirement already satisfied: email-validator==1.1.3 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 21)) (1.1.3)
Requirement already satisfied: et-xmlfile==1.1.0 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 22)) (1.1.0)
Requirement already satisfied: exchangerates==0.3.4 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 23)) (0.3.4)
Requirement already satisfied: fuzzywuzzy==0.18.0 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 24)) (0.18.0)
Requirement already satisfied: greenlet==1.1.1 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 25)) (1.1.1)
Requirement already satisfied: hdx-python-api==5.2.4 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 26)) (5.2.4)
Requirement already satisfied: hdx-python-country==2.9.5 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 27)) (2.9.5)
Requirement already satisfied: hdx-python-utilities==2.6.9 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 28)) (2.6.9)
Requirement already satisfied: html5lib==1.1 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 29)) (1.1)
Requirement already satisfied: idna==3.2 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 30)) (3.2)
Requirement already satisfied: ijson==3.1.4 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 31)) (3.1.4)
Requirement already satisfied: inflect==5.3.0 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 32)) (5.3.0)
Requirement already satisfied: iniconfig==1.1.1 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 33)) (1.1.1)
Requirement already satisfied: itsdangerous==2.0.1 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 34)) (2.0.1)
Requirement already satisfied: jmespath==0.10.0 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 35)) (0.10.0)
Requirement already satisfied: jsonlines==2.0.0 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 36)) (2.0.0)
Requirement already satisfied: jsonpath-ng==1.5.3 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 37)) (1.5.3)
Requirement already satisfied: libhxl==4.24.1 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 38)) (4.24.1)
Requirement already satisfied: linear-tsv==1.1.0 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 39)) (1.1.0)
Requirement already satisfied: lxml==4.6.3 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 40)) (4.6.3)
Requirement already satisfied: macholib==1.15.1 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 41)) (1.15.1)
Requirement already satisfied: ndg-httpsclient==0.5.1 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 42)) (0.5.1)
Requirement already satisfied: num2words==0.5.10 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 43)) (0.5.10)
Requirement already satisfied: openpyxl==3.0.7 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 44)) (3.0.7)
Requirement already satisfied: packaging==21.0 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 45)) (21.0)
Requirement already satisfied: pluggy==0.13.1 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 46)) (0.13.1)
Requirement already satisfied: ply==3.11 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 47)) (3.11)
Requirement already satisfied: pprintpp==0.4.0 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 48)) (0.4.0)
Requirement already satisfied: prompt-toolkit==3.0.19 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 49)) (3.0.19)
Requirement already satisfied: py==1.10.0 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 50)) (1.10.0)
Requirement already satisfied: pyasn1==0.4.8 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 51)) (0.4.8)
Requirement already satisfied: pycountry==20.7.3 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 52)) (20.7.3)
Requirement already satisfied: pycountry-convert==0.7.2 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 53)) (0.7.2)
Requirement already satisfied: pycparser==2.20 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 54)) (2.20)
Requirement already satisfied: pyinstaller==4.5.1 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 55)) (4.5.1)
Requirement already satisfied: pyinstaller-hooks-contrib==2021.3 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 56)) (2021.3)
Requirement already satisfied: pyOpenSSL==20.0.1 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 57)) (20.0.1)
Requirement already satisfied: pyparsing==2.4.7 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 58)) (2.4.7)
Requirement already satisfied: pyphonetics==0.5.3 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 59)) (0.5.3)
Requirement already satisfied: pyquery==1.4.3 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 60)) (1.4.3)
Requirement already satisfied: pytest==6.2.4 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 61)) (6.2.4)
Requirement already satisfied: pytest-cov==2.12.1 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 62)) (2.12.1)
Requirement already satisfied: pytest-mock==3.6.1 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 63)) (3.6.1)
Requirement already satisfied: python-dateutil==2.8.2 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 64)) (2.8.2)
Requirement already satisfied: python-io-wrapper==0.2 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 65)) (0.2)
Requirement already satisfied: python-Levenshtein-wheels==0.13.2 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 66)) (0.13.2)
Requirement already satisfied: python-slugify==5.0.2 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 67)) (5.0.2)
Requirement already satisfied: PyYAML==5.4.1 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 68)) (5.4.1)
Requirement already satisfied: quantulum3==0.7.7 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 69)) (0.7.7)
Requirement already satisfied: questionary==1.10.0 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 70)) (1.10.0)
Requirement already satisfied: ratelimit==2.2.1 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 71)) (2.2.1)
Requirement already satisfied: repoze.lru==0.7 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 72)) (0.7)
Requirement already satisfied: requests==2.26.0 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 73)) (2.26.0)
Requirement already satisfied: requests-cache==0.7.3 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 74)) (0.7.3)
Requirement already satisfied: requests-file==1.5.1 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 75)) (1.5.1)
Requirement already satisfied: ruamel.yaml==0.17.10 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 76)) (0.17.10)
Requirement already satisfied: ruamel.yaml.clib==0.2.6 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 77)) (0.2.6)
Requirement already satisfied: s3transfer==0.5.0 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 78)) (0.5.0)
Requirement already satisfied: six==1.16.0 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 79)) (1.16.0)
Requirement already satisfied: soupsieve==2.2.1 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 80)) (2.2.1)
Requirement already satisfied: SQLAlchemy==1.4.22 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 81)) (1.4.22)
Requirement already satisfied: tabulator==1.53.5 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 82)) (1.53.5)
Requirement already satisfied: text-unidecode==1.3 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 83)) (1.3)
Requirement already satisfied: toml==0.10.2 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 84)) (0.10.2)
Requirement already satisfied: tqdm==4.62.0 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 85)) (4.62.0)
Requirement already satisfied: unicodecsv==0.14.1 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 86)) (0.14.1)
Requirement already satisfied: Unidecode==1.2.0 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 87)) (1.2.0)
Requirement already satisfied: url-normalize==1.4.3 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 88)) (1.4.3)
Requirement already satisfied: urllib3==1.26.6 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 89)) (1.26.6)
Requirement already satisfied: wcwidth==0.2.5 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 90)) (0.2.5)
Requirement already satisfied: webencodings==0.5.1 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 91)) (0.5.1)
Requirement already satisfied: websocket-client==1.2.1 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 92)) (1.2.1)
Requirement already satisfied: xlrd==2.0.1 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 93)) (2.0.1)
Requirement already satisfied: xlrd3==1.1.0 in /home/lance/.local/lib/python3.10/site-packages (from -r kuwala/core/cli/requirements.txt (line 94)) (1.1.0)
Requirement already satisfied: setuptools in /home/lance/.local/lib/python3.10/site-packages (from ckanapi==4.6->-r kuwala/core/cli/requirements.txt (line 12)) (60.8.2)
Requirement already satisfied: wheel in /home/lance/.local/lib/python3.10/site-packages (from libhxl==4.24.1->-r kuwala/core/cli/requirements.txt (line 38)) (0.37.1)
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/lance/opensource/kuwala
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Installing collected packages: kuwala
  Running setup.py develop for kuwala
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [1 lines of output]
        ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [1 lines of output]
    ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by IritaSee** [comment]
Hello @Lance0404 ! Thank you for trying and we are sorry for the inconvenience. 

As it for now, we are still trying our best to solve *every* Windows OS related issue with #70 . Since the pull request is not ready yet, we encourage you to run `sh kuwala/scripts/initialize_windows.sh` first. This script meant to 'translate' all the utility script to something readable on Windows system and put all of the translated script to  `/windows`

So after that, we adapt a bit to the change, means we need to run:
`cd kuwala/scripts/windows && sh initialize_core_components.sh && sh run_cli.sh`

**Comment by Lance0404** [comment]
Hi @IritaSee , tried but results the same.
